"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
```python
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s_set = set()
        for i in range(len(s)):
            s_set.add(t[i])
        
        for k in range(len(t)):
            if t[k] not in s_set:
                return t[k]
```
"""
Input:
"a"
"aa"
Output:
null
Expected:
"a"
"""
